### ISSUE TITLE
Avoid confusion with github links vs filenames

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#12]
How about we remove the github links in the excel sheets since it's just super confusing! 
The name of the module has to follow the actual filename (plus optional Prefix eg `UC2_`, postfix `_v3`) and mandatory filetype `.stl`.

**Comment by b286** [comment]
The github links of the STL files? We can delete them if they're redundant. But I'd like to keep the column and and the links to the externam parts in it, since this is where all the latest parts are listed in one place.

**Comment by beniroquai** [comment]
I have removed them from the Excel sheet. 

For now, the files in the STL folder and in the CAD folder have to follow the exact naming convention from the Excelsheet.
