### ISSUE TITLE
Having a main figure (with same filename) in each module folder

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#13]
Instead of placing hard-coded figure URLs in the excelsheet I think it would be nice to have a "cover.png" for each module in the `MODULE/IMAGE` folder. This makes things easier. 
What do you think @b286

**Comment by b286** [comment]
This can be easily done. I'd suggest to also make them rather small, to be just a supportive info any not consume much space and loading time or whatever. Shall I?

**Comment by beniroquai** [comment]
It is done. I have just copied and rennamed some figures. feel free to add it. 

Looks like this:
![image](https://user-images.githubusercontent.com/4345528/104323368-60e89a80-54e6-11eb-99c8-a3067fbb0192.png)

**Comment by b286** [comment]
After 'Delete all' and switching to 'None' the last picture is stil hanging there. 

<img width="1920" alt="Screenshot 2021-01-12 16 29 13" src="https://user-images.githubusercontent.com/44977563/104335019-4a950b80-54f3-11eb-99aa-90c5bd9e8fca.png">

**Comment by beniroquai** [comment]
Fixed. Thanks
