### ISSUE TITLE
Applications show an extra module 

### ISSUE THREAD

**Issue by b286** [bionanoimaging/uc2-configurator#14]
In most applications, in the list of necessary modules appears an extra one in the end - it doesn't contribute to the STL list and the zip file though. 

There is no reason for this in the excel sheet, that one is correct in this matter. 

Example: Double-slit experiment. 
<img width="1920" alt="Screenshot 2021-01-12 10 03 33" src="https://user-images.githubusercontent.com/44977563/104292803-92993b80-54bd-11eb-9a3f-dfe5fcab247c.png">
This extra module also changes as described in issue #4 
<img width="1920" alt="Screenshot 2021-01-12 10 13 52" src="https://user-images.githubusercontent.com/44977563/104293853-cb85e000-54be-11eb-837d-ee5b9ac2ed15.png">

**Comment by beniroquai** [comment]
Fixed
