### ISSUE TITLE
Current List of available modules vs. Excel Sheet

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#19]
- [ ] APP_openXY
- [ ] APP_Ptychogrphy
- [ ] APP_SIMPLE-Telescope
- [ ] ASSEMBLY_Baseplate
- [ ] ASSEMBLY_CUBE_AlliedVision_Alvium
- [ ] ASSEMBLY_CUBE_Aperture_Circular
- [ ] ASSEMBLY_CUBE_Aperture_Rectangular
- [ ] ASSEMBLY_CUBE_Base
- [ ] ASSEMBLY_CUBE_Base_v2
- [ ] ASSEMBLY_CUBE_BaslerCam
- [ ] ASSEMBLY_CUBE_Beamexpander
- [ ] ASSEMBLY_CUBE_Beamexpander_v2
- [ ] ASSEMBLY_CUBE_Beamsplitter
- [ ] ASSEMBLY_CUBE_Beamsplitter_v2
- [ ] ASSEMBLY_CUBE_Cellphonemount
- [ ] ASSEMBLY_CUBE_Dichroic_Beamsplitter
- [ ] ASSEMBLY_CUBE_Dichroic_Beamsplitter_v2
- [ ] ASSEMBLY_CUBE_Eyeball
- [ ] ASSEMBLY_CUBE_Eyepiece
- [ ] ASSEMBLY_CUBE_Eyepiece_v2
- [ ] ASSEMBLY_CUBE_Flashlight
- [ ] ASSEMBLY_CUBE_Laser
- [ ] ASSEMBLY_CUBE_Laser_v2
- [ ] ASSEMBLY_CUBE_LED
- [ ] ASSEMBLY_CUBE_LED_Matrix
- [ ] ASSEMBLY_CUBE_LED_Matrix_v2
- [ ] ASSEMBLY_CUBE_LED_Ring_v2
- [ ] ASSEMBLY_CUBE_LED_v2
- [ ] ASSEMBLY_CUBE_Lens
- [ ] ASSEMBLY_CUBE_Lens_CYLINDRICAL
- [ ] ASSEMBLY_CUBE_Lens_CYLINDRICAL_v2
- [ ] ASSEMBLY_CUBE_Lens_large
- [ ] ASSEMBLY_CUBE_Lens_objective
- [ ] ASSEMBLY_CUBE_Lens_small
- [ ] ASSEMBLY_CUBE_Mirror_45
- [ ] ASSEMBLY_CUBE_Mirror_45_Thorlabs
- [ ] ASSEMBLY_CUBE_Mirror_Kinematic
- [ ] ASSEMBLY_CUBE_Mirror_Kinematic_45
- [ ] ASSEMBLY_CUBE_RaspiCam
- [ ] ASSEMBLY_CUBE_S-STAGE_v2
- [ ] ASSEMBLY_CUBE_S-STAGE_v2.1
- [ ] ASSEMBLY_CUBE_Sample_Comb
- [ ] ASSEMBLY_CUBE_Sample_Holder
- [ ] ASSEMBLY_CUBE_Sample_Holder_v2
- [ ] ASSEMBLY_CUBE_Thorlabs
- [ ] ASSEMBLY_CUBE_Thorlabs_v2
- [ ] ASSEMBLY_CUBE_Z-STAGE_mechanical
- [ ] ASSEMBLY_CUBE_Z-STAGE_objective
- [ ] ASSEMBLY_CUBE_Z-STAGE_sample
- [ ] ASSEMBLY_CUBE_Z-STAGE_v2
- [ ] ASSEMBLY_CUBE_Z-STAGE_v3
- [ ] ASSEMBLY_XYZ-STAGE
- [ ] ASSEMBLY_XYZ-STAGE_v0
- [ ] CUBE_EmptyTemplate
- [ ] CUBE_INSERT_Fluomodule
- [ ] CUBE_INSERT_OpenFlexure
- [ ] CUBE_INSERT_OpenFlexure_Deltastage
- [ ] CUBE_INSERT_OpenFlexure_Deltastage_v2
- [ ] CUBE_INSERT_OpenFlexure_v2
- [ ] CUBE_INSERT_Thorlabsmount
- [ ] CUBE_Lensholder
- [ ] EXT_Alignment_Tool
- [ ] EXT_ELECTRONICS-Mount
- [ ] EXT_ELECTRONICS-RaspiTFT-Case
- [ ] IMAGES
- [ ] OLD
- [ ] RAW

----------

- [ ] ASSEMBLY_Baseplate
- [ ] ASSEMBLY_CUBE_Base
- [ ] ASSEMBLY_CUBE_AlliedVision_Alvium
- [ ] ASSEMBLY_CUBE_Aperture_Circular
- [ ] ASSEMBLY_CUBE_Aperture_Rectangular
- [ ] ASSEMBLY_CUBE_BaslerCam
- [ ] ASSEMBLY_CUBE_Beamexpander
- [ ] ASSEMBLY_CUBE_Beamsplitter
- [ ] ASSEMBLY_CUBE_Dichroic_Beamsplitter
- [ ] ASSEMBLY_CUBE_Eyeball
- [ ] ASSEMBLY_CUBE_Eyepiece
- [ ] ASSEMBLY_CUBE_Flashlight
- [ ] ASSEMBLY_CUBE_LED_Matrix
- [ ] ASSEMBLY_CUBE_LED
- [ ] ASSEMBLY_CUBE_Laser
- [ ] ASSEMBLY_CUBE_Lens_CYLINDRICAL
- [ ] ASSEMBLY_CUBE_Lens_objective
- [ ] ASSEMBLY_CUBE_Lens_small
- [ ] ASSEMBLY_CUBE_Lens_large
- [ ] ASSEMBLY_CUBE_Mirror_45
- [ ] ASSEMBLY_CUBE_Mirror_45_Thorlabs
- [ ] ASSEMBLY_CUBE_Mirror_Kinematic_45
- [ ] ASSEMBLY_CUBE_Mirror_Kinematic
- [ ] ASSEMBLY_CUBE_RaspiCam
- [ ] ASSEMBLY_CUBE_S-STAGE_v2.1
- [ ] ASSEMBLY_CUBE_Sample_Holder
- [ ] ASSEMBLY_CUBE_Sample_Comb
- [ ] ASSEMBLY_CUBE_Z-stage_mechanical
- [ ] ASSEMBLY_CUBE_Z-stage_sample
- [ ] Raspberry Pi +   accesories

**Comment by beniroquai** [comment]
Can we please arrange a meeting to write the documentation how to add a module "properly" and make sure that the gap between existing and accessible parts shrinks? 
CC: @ranranking @b286

**Comment by ranranking** [comment]
Sure, I am fine with it. This week or next week?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Benedict Diederich <notifications@github.com>
发送时间: Tuesday, January 12, 2021 12:52:48 PM
收件人: bionanoimaging/uc2-configurator <uc2-configurator@noreply.github.com>
抄送: ranranking <wanghaoran1207@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [bionanoimaging/uc2-configurator] Current List of available modules vs. Excel Sheet (#19)


Can we please arrange a meeting to write the documentation how to add a module "properly" and make sure that the gap between existing and accessible parts shrinks?
CC: @ranranking<https://github.com/ranranking> @b286<https://github.com/b286>

―

**Comment by b286** [comment]
Sure, when? 

I'd like to just point out that the correct list of modules we want to have is in v3 branch, in master is still plenty of old stuff.
