### ISSUE TITLE
v2 v3 issue

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#20]
or v3 I omitted the version from the name of the module, since renaming everything everywhere is a hassle and this will save time in the future. However, all the modules that existed in git with ‘_v2’ in their name now appeared extra in the configurator and their folders also appeared again in the git CAD folder, with the only file in them being the ‘config.json’. The ‘_v2’ options in the configurator contain the v3 inserts that correspond to the module but not the cube and lid

**Comment by beniroquai** [comment]
Yes, everything should be cleaned up now. Now `v3` `v2`post-fix anymore..
Yet I see some `v2.1`?

**Comment by b286** [comment]
That one's intentional. The others change with the new version while this one is stopped the way it was used the last time, yet compatible.

**Comment by beniroquai** [comment]
I see. Closing for now.
