### ISSUE TITLE
Adding openSIM and openISM to the Excel sheet

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#23]
I think it's worth adding more sophisticated setups to the excel sheet, what do you think @b286 @ranranking ?

**Comment by b286** [comment]
If they're meant to be easily accessible and built by anyone, then we should add them.

**Comment by beniroquai** [comment]
With respect to the paper.. yes.

**Comment by beniroquai** [comment]
@ranranking would you mind having a look at it if this is plausible? 
At least the modules :)
The Excel Database can be found [here](https://github.com/bionanoimaging/UC2-GIT/blob/v3/DOCUMENTS/UC2-Configurator/UC2_ReadyToUse_Boxes_Modules_Parts.xlsx)
You can add the openSIM and openISM module to the very bottom line if you want :)

**Comment by ranranking** [comment]
Roger! I will try to sum it in.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Benedict Diederich <notifications@github.com>
发送时间: Wednesday, January 13, 2021 8:18:07 PM
收件人: bionanoimaging/uc2-configurator <uc2-configurator@noreply.github.com>
抄送: ranranking <wanghaoran1207@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [bionanoimaging/uc2-configurator] Adding openSIM and openISM to the Excel sheet (#23)


@ranranking<https://github.com/ranranking> would you mind having a look at it if this is plausible?
At least the modules :)
The Excel Database can be found here<https://github.com/bionanoimaging/UC2-GIT/blob/v3/DOCUMENTS/UC2-Configurator/UC2_ReadyToUse_Boxes_Modules_Parts.xlsx>
You can add the openSIM and openISM module to the very bottom line if you want :)

―

**Comment by beniroquai** [comment]
All done. Thans @ranranking
