### ISSUE TITLE
Adding cover images to BOXes 

### ISSUE THREAD

**Issue by b286** [bionanoimaging/uc2-configurator#27]
They all have a picture called 'cover.png' in their respective image folders (like UC2-GIT\TheBOX\SimpleBOX\IMAGES). Not sure if the different path is not an issue.

**Comment by b286** [comment]
All BOXes have now their cover.jpg in their place holder folders in APPLICATIONS, the path is therefore the same as all the other APPs.

**Comment by beniroquai** [comment]
Nice! I think it works now for most (if not all) Assemblies, or?
