### ISSUE TITLE
Issue when adding modules

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#3]
when adding a module of choice to an application, list and folder are again empty

**Comment by beniroquai** [comment]
could be an issue with missing puzzle piece which doesnt exist on github..; was a problem with the puzzle pieces and the code; I wonder why it worked in the first place

**Comment by b286** [comment]
Now when downloading the Application works, it is not possible to download a single module or add it when an Application is selected. The module doesn't appear in the list, nor in the downloaded zip file. 

A zip file with selected modules only is empty.

**Comment by beniroquai** [comment]
Should be fixed now.
