### ISSUE TITLE
Different results on different clicks

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#4]
The applications sometimes give a different list of modules - the first time I selected an application there was a certain list. In some cases, from the second time on, there was a difference in either the first or the last module in the list.

**Comment by beniroquai** [comment]
hard to reproduce, please show me @b286

**Comment by b286** [comment]
It is hard to reproduce. The thing is that it behaves strangely when switching between the Applications. 

Example: 
chosen Incubator microscope. Last module is an extra Mirror 45
<img width="1920" alt="Screenshot 2021-01-12 10 06 27" src="https://user-images.githubusercontent.com/44977563/104293106-eb68d400-54bd-11eb-84f4-9a923500dead.png">
switched to None and back to incubator. Last module is an extra Assembly Base
<img width="1920" alt="Screenshot 2021-01-12 10 06 59" src="https://user-images.githubusercontent.com/44977563/104293121-f15eb500-54bd-11eb-9628-23b1aba6ec23.png">
switched to None and back to incubator again. Last module is an extra Raspicam. 
<img width="1920" alt="Screenshot 2021-01-12 10 07 37" src="https://user-images.githubusercontent.com/44977563/104293131-f58ad280-54bd-11eb-993a-e604ad8b67c0.png">
The Raspican stays as the last one for all the next times. 

From the list of the STLs it is apparent that in reality the last module is the Z-stage.

**Comment by beniroquai** [comment]
Was solved with checking if the module is properly loaded or not. Not nice, but works.
