### ISSUE TITLE
Missing components in the modules

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#6]
# Abbe experiment: 

-missing: 14x baseplate puzzle, 5x lens
-extra: 1x Sample holder

# Double-slit: 

-missing: 4x baseplate puzzle
-extra: 1x Sample holder

# In-line hologram: 

-missing: 4x baseplate puzzle
-extra: 1x RasPi Camera

# Incubator Microscope: 

-missing: 5x baseplate puzzle, 1x Z-stage
-extra: 1x Mirror 45

# Incubator Microscope fluorescence: 

-strange list, the APP should be anyways either updated or fused into the other one. Plus there’s another fluorescent microscope now and it became confusing 

# Light sheet: 

-missing: 15x baseplate puzzle, 1x Cylindrical lens, 2x Objective lens
-extra: 1x S-stage

# Mach-Zehnder: 

-missing: 11x baseplate puzzle
-extra: 1x Beam splitter 

# Michelson: 
-missing: 7x baseplate puzzle
-extra: 1x kinematic mirror

# Simple projector: 
-missing: 3x baseplate puzzle, 1x lens, (1xflashlight)
-extra: 

# Simple smartphone microscope: 
-I should split it and make two list - for the mechanical-only one and the one with electronics
-missing: 8x baseplate puzzle, 1x Z-stage
-extra: 1x Sample holder 

# Simple telescope: 
-missing: 8x baseplate puzzle, 4x Lens (it’s empty)
-extra: 

# Smartphone microscope:
-missing: 8x baseplate puzzle, 1x Sample holder, 1x Z-stage, 2x empty cube
-extra: 1x mirror 45

# Spectrometer: 
-missing: 6x baseplate puzzle, 1x Objective lens
-extra: 1x Sample holder

**Comment by beniroquai** [comment]
In general: The script just populates what's in the excel sheet. There was an issue with the baseplate for example. It didn't exist. 

Each part in the Excel sheet has to be named exactly (!) like the STL in the `CAD/RAW/STL` folder **PLUS:** Prefix + Postfix

**Comment by beniroquai** [comment]
Also: `ASSEMBLY_CUBE_Base` vs `ASSEMBLY_CUBE_Empty` @b286

**Comment by beniroquai** [comment]
Flashlight Github URL Missing

**Comment by beniroquai** [comment]
Cylindrical lens missing

**Comment by b286** [comment]
All folders are now in Git, also the Sample holder is split. The excel sheet tells the correct number of modules for each App. 

But I'm still not sure about the naming: You say the STLs have to have exactly the same name but the excel is not using the prefixes.
