### ISSUE TITLE
Missing ASSEMBLY_CUBE_Lens_objective

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/uc2-configurator#9]
I created a new empty folder `ASSEMBLY_CUBE_Lens_objective`.. we can refer to the `ASSEMBLY_CUBE_Lens`
But the configurator needs to have it to be happy

**Comment by b286** [comment]
I'll organise the 'extra' folders to link to the root one, so configurator can have them but they don't confuse a user.
